### ISSUE TITLE
Dynamic Process Name Resolution

### ISSUE THREAD

**Issue by ppenna** [cart-pucminas/bluedragon-system#9]
**Description**

Currently, the naming service relies on a static scheme  for resolving processes names.

To enable maximum flexibility, we should add an interface for dynamically adding, querying and removing names from the naming table.

**Roadmap**

- [ ] Deploy a stand alone naming service.
- [ ] Introduce a function to dynamically add a name to the naming table.
- [ ] Write a routine for querying process names.
- [ ] Add a functionality for removing a name from the naming table.
- [ ] Update the naming service client accordingly to rely on the above functionalities.
